import type { Factory } from '@/src/features/factory/domain/factory.ts';
import { FEATURE_STATE } from '@/src/features/factory/states/featureState.ts';
import { WALLET_STATE } from '@/src/features/factory/states/walletState.ts';

export const FACTORY_STATE: Factory = {
  cash: 0,
  cashRef: 0,
  clip: 0,
  clipFactory: 0,
  clipFactoryCost: 1e5,
  clipPerSecond: 0,
  clipPrice: 0.2,
  clipPriceRef: 0.2,
  creativity: 0,
  drone: 50,
  feature: FEATURE_STATE,
  funds: 0,
  fundsPerSecond: 0,
  harvesterDrone: 0,
  harvesterDroneCost: 1e4,
  clipper: 0,
  clipperBonus: 0,
  clipperCost: 5,
  marketing: 0,
  marketingBonus: 0,
  marketingCost: 100,
  megaClipper: 0,
  megaClipperBonus: 0,
  megaClipperCost: 5e2,
  memory: 1,
  operation: 0,
  operationMax: 7e2,
  processor: 1,
  publicDemand: 0.5,
  swarmGifts: 0,
  swarmStatus: 0,
  swarmStrategy: 5,
  trust: 0,
  trustRef: 0,
  unsoldInventory: 0,
  unsoldInventoryBonus: 0,
  wallet: WALLET_STATE,
  wire: 100,
  wireBonus: 100,
  wireCost: 20,
  wireDrone: 0,
  wireDroneCost: 1e4,
  yomi: 1e4,
};
